### ISSUE TITLE
Links to windows applications not working

### ISSUE THREAD

**Issue by hmaarrfk** [chrisjbillington/desktop-app#13]
I'm using desktop-app version 0.2.6 and trying to create a shortcut for a windows application.

However, because the shotcut doesn't include the `.exe` at the end, it fails to launch.

```
> conda list
#
# Name                    Version                   Build  Channel
desktop-app               0.2.6            py38h885f38d_3    conda-forge
```

I had to modify the application with the following tiny patch:
```patch
diff --git a/desktop_app/windows.py b/desktop_app/windows.py
index eb4f2ab..3c14597 100644
--- a/desktop_app/windows.py
+++ b/desktop_app/windows.py
@@ -74,7 +74,7 @@ def create_shortcut(
     _checkwindows()
     objShell = Dispatch('WScript.Shell')
     shortcut = objShell.CreateShortcut(str(shortcut_path))
-    shortcut.TargetPath = str(target)
+    shortcut.TargetPath = str(target) + '.exe'
     if arguments:
         shortcut.Arguments = list2cmdline(arguments)
     if working_directory is not None:
```

Are you seeing the same thing?

**Comment by chrisjbillington** [comment]
No, I don't see this. What version of Windows are you on? This occurs when you run `desktop-app install <modulename>`?

(apologies, I haven't yet documented that `desktop-app install <modulename>` is the intended usage, I've been slack on documentation since this project was made to serve the needs of another project!)

If adding the ".exe" is harmless, then I'll make your suggested change - after investigating a little bit!

**Comment by hmaarrfk** [comment]
Thanks for responding so quickly!

I agree that this is a pretty powerful enabling project!

I skipped the install part on Linux, but on windows, creating `lnk` files is not my favorite thing to do.

You are correct in saying that this occurs when I run
```
desktop-app install my_module.submodule
```

The script name shows up as not having the `.exe` which is causing things to fail at linking on my windows Machine.

I'm on Windows 10

![image](https://user-images.githubusercontent.com/90008/109732945-2321fd00-7b8c-11eb-8186-ab5dc3f5c7aa.png)

**Comment by hmaarrfk** [comment]
I'm not so sure it is harmless since the `.exe` might be double added for your version maybe.

**Comment by chrisjbillington** [comment]
Ok, I have a theory.

My extensions *do* have `.exe` in them, even though the code creating the shortcuts clearly does not pass in a `TargetPath` ending in `.exe`.

This makes me think that this Windows shortcut API is automatically appending `.exe` for me, in my case. But it isn't for you. Why not?

I think it's probably because you are using a submodule, whereas in the example I checked, it's just a top-level module. So your launcher script already has a dot in its name (`module.submodule`). This automatic behaviour of the Windows API must simply check whether there is a dot in the name already, as it interprets any dot as indicative of an extension, so it decides not to append `.exe`.

So I think explicitly appending `.exe` should be fine and not double up, I'll go ahead and push a commit.

**Comment by hmaarrfk** [comment]
Thanks @chrisjbillington I really appreciate it!

**Comment by chrisjbillington** [comment]
No worries, appreciate the bug report!

If you'd like to test the change, you can install a build from git master with:

```
conda install -c labscript-suite/label/test desktop-app
```

**Comment by hmaarrfk** [comment]
Do you mind if i do the bad thing and upload a patched version:
https://github.com/conda-forge/desktop-app-feedstock/pull/7

I guess I can upload and build to my own channel instead. let me do that.

**Comment by chrisjbillington** [comment]
I'll just stamp a new patch version, makes it easier for everyone.

**Comment by hmaarrfk** [comment]
^_^ right, i noticed that you were updating your release process so i didn't feel like overburdening you incase you didn't have the chance to get it completed within the next few days.

**Comment by chrisjbillington** [comment]
Fair enough! The release issues were actually a nightmare to fix, but since I already went through that turmoil ages ago with another project, it was quick to apply the same fix here!

Version 0.2.7 has been tagged.
