### ISSUE TITLE
Should `.py` be added to the launcher by default?

### ISSUE THREAD

**Issue by hmaarrfk** [chrisjbillington/desktop-app#15]
https://github.com/chrisjbillington/desktop-app/blob/332ae72e61b554c38f4add03c10aebec6cfb5419/desktop_app/launcher.py#L54-L57

Presently, a test is added to check if the module is a directory.

However, we would like to create a few scripts within a given directory desktop-app could launch.

I think the statement
```
if is_dir():
     # as before
else:
    script_path = script_path.parent / (script_path.name + '.py')
```
should work. I'm not sure if you use scripts or only top level apps.

**Comment by chrisjbillington** [comment]
I intended desktop-app to be able to launch any script that can be run with `python -m <whatever.whatever>`, so it looks like it's just a bug that I didn't append the `.py` there. I have not sufficiently tested with all kinds of scripts, so I appreciate the bug reports!

I'll add the extension.

**Comment by hmaarrfk** [comment]
I don't think that `with_suffix` is the correct choice since it will overwrite `package.subpackage.actual_script` to `package.subpackage.py`

**Comment by hmaarrfk** [comment]
you are fast at 8am...

**Comment by chrisjbillington** [comment]
I actually didn't realise `with_suffix` *replaces* existing suffixes, however, `package.subpackage.actual_script` should already be split into `Path('package/subpackage/actual_script')` at that point, so I don't think there can be any dots in the last part. All dots have already been removed:
```python
script_path = Path(package_directory, *module_name.split('.')[1:])
```
So that's actually fine, right?

> you are fast at 8am...

Am definitely not normally a morning person :p. My cat woke me up so I decided to stay up and watch the SpaceX SN10 test flight. Which got delayed, but anyway.

**Comment by hmaarrfk** [comment]
hmm, you are right. your stuff works by python standards. scripts shouldn't have dots in the names.

**Comment by hmaarrfk** [comment]
Any chance of a tag?

Almost done wrapping out the desktop-app migration on my work and I want to find a good resting place for the entry points 😄

**Comment by chrisjbillington** [comment]
Sure, tag pushed! Will be a new version on PyPI once the release workflow runs (it is very slow, takes ~20 - 30 minutes).

**Comment by hmaarrfk** [comment]
nice thanks!
