### ISSUE TITLE
MSCV required to install desktop-app on windows for python 3.10

### ISSUE THREAD

**Issue by linuxrider** [chrisjbillington/desktop-app#24]
It is quite cumbersome to use desktop-app on windows with python 3.10 due to missing wheel which entails installing MSVC.
Furthermore, d89403b5384d66fdf8b47be853e66fd50d867514 seems important for winpython environments.
#23 restricts macos runner image to 10.15 which allows a successful run of the build pipeline again.

Are there any plans to make a new release in the near future?

**Comment by chrisjbillington** [comment]
Thanks @linuxrider, yes, the project is still active and I'll endeavour to make a release soon!

I'd like to extend the changes in 3701c2b28b6fc89e5dfa76888f1ab5407daa1c76 to work with editable installs and projects that use a src layout, otherwise that fix is a bit limited. I'll take a look at that and then hopefully get a release out in short order.

Thanks for getting the macos build working again - pinning the version seems like it maybe just kicks the can down the road a bit so hopefully I can figure out how to make it work with the latest macos when I have time. It's possible the xcode workaround isn't even necessary anymore, I don't know.

**Comment by linuxrider** [comment]
@chrisjbillington Thanks for looking into it!
Regarding MacOS: I also thought that the workaround could be obsolete and tried quite some combinations of runner image and xcode version. However, I could not find any working combination which worked.

**Comment by chrisjbillington** [comment]
Ok, I've fixed what I wanted to fix, and released v0.3.0 with wheels built for Python 3.10. Let me know if there are any issues.

Can't do 3.11 quite yet as the requisite conda packages aren't available - that usually lags a bit, and if it lags more than a few months I'll go ahead and build the wheels for 3.11 at least. Still figuring out how to best keep many Python projects with impure wheels up to date with the annual Python releases, need to figure out how to automate that.

Thanks again for the help.
